// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/controller-runtime/pkg/recorder (interfaces: EventRecorder)
//
// Generated by this command:
//
//	mockgen -destination pkg/mocks/events/mock.go sigs.k8s.io/controller-runtime/pkg/recorder EventRecorder
//

// Package mock_recorder is a generated GoMock package.
package mock_recorder

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// MockEventRecorder is a mock of EventRecorder interface.
type MockEventRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockEventRecorderMockRecorder
	isgomock struct{}
}

// MockEventRecorderMockRecorder is the mock recorder for MockEventRecorder.
type MockEventRecorderMockRecorder struct {
	mock *MockEventRecorder
}

// NewMockEventRecorder creates a new mock instance.
func NewMockEventRecorder(ctrl *gomock.Controller) *MockEventRecorder {
	mock := &MockEventRecorder{ctrl: ctrl}
	mock.recorder = &MockEventRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRecorder) EXPECT() *MockEventRecorderMockRecorder {
	return m.recorder
}

// AnnotatedEventf mocks base method.
func (m *MockEventRecorder) AnnotatedEventf(regarding, related runtime.Object, annotations map[string]string, eventtype, reason, action, note string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{regarding, related, annotations, eventtype, reason, action, note}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AnnotatedEventf", varargs...)
}

// AnnotatedEventf indicates an expected call of AnnotatedEventf.
func (mr *MockEventRecorderMockRecorder) AnnotatedEventf(regarding, related, annotations, eventtype, reason, action, note any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{regarding, related, annotations, eventtype, reason, action, note}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnnotatedEventf", reflect.TypeOf((*MockEventRecorder)(nil).AnnotatedEventf), varargs...)
}

// Eventf mocks base method.
func (m *MockEventRecorder) Eventf(regarding, related runtime.Object, eventtype, reason, action, note string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{regarding, related, eventtype, reason, action, note}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Eventf", varargs...)
}

// Eventf indicates an expected call of Eventf.
func (mr *MockEventRecorderMockRecorder) Eventf(regarding, related, eventtype, reason, action, note any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{regarding, related, eventtype, reason, action, note}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eventf", reflect.TypeOf((*MockEventRecorder)(nil).Eventf), varargs...)
}
