version: 2
builds:
  - skip: true
    main: ./cmd/generic/main.go
    ldflags:
      - -s -w -X github.com/bakito/batch-job-controller/version.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
