before:
  hooks:
    - helm package ./helm/example-batch-job-controller/ --version v{{ .Version }} --app-version v{{ .Version }} -d ./
builds:
  - skip: true
    main: ./cmd/generic/main.go
    ldflags:
      - -s -w -X github.com/bakito/batch-job-controller/version.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  extra_files:
    - glob: ./dependency-licenses.csv
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
