# Default values for batch-job-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: example-job-controller

deployment:
  replicas: 1
  image: ghcr.io/bakito/batch-job-controller
  imageTag:
  cronexpression: "* * * * *"
  reportDirectory: "/var/www"
  reportHistory: 10 # number of reports to be used
  podPoolSize: 10 # number of pods allowed to run parallel
  runOnStartup: false
  withPersistentVolume: true
  storageClassName: ""
  labels:
  annotations:
  env:


routes:
  metrics: true
  internal: true

jobPod:
  image: registry.access.redhat.com/ubi8/ubi