# Default values for batch-job-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: example-job-controller

deployment:
  replicas: 1
  image: quay.io/bakito/batch-job-controller
  cronexpression: "* * * * *"
  reportHistory: 10 # number of reports to be used
  podPoolSize: 10 # number of pods allowed to run parallel
  runOnStartup: false
  withPersistentVolume: true
  storageClassName: ""
  labels: {}


monitoring: {}

route:
  metrics: true
  internal: true