apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "batch-job-controller.name" . }}
{{ include "batch-job-controller.helm-labels" . | indent 4 }}
  name: {{ template "batch-job-controller.name" . }}-reports
  namespace: {{ .Release.Namespace }}
spec:
  host: "openscap-{{ .Release.Namespace }}.{{ .Values.route.hostSuffix }}"
  port:
    targetPort: public
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "batch-job-controller.name" . }}
    weight: 100
status:
  ingress: []