{{- if .Values.route.internal -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "batch-job-controller.name" . }}
{{ include "batch-job-controller.helm-labels" . | indent 4 }}
  name: {{ template "batch-job-controller.name" . }}-internal
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ template "batch-job-controller.name" . }}-internal-{{ .Release.Namespace }}.{{ .Values.route.hostSuffix }}
  path: /debug/pprof/
  port:
    targetPort: internal
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "batch-job-controller.name" . }}
    weight: 100
status:
  ingress: []
{{- end -}}