apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "batch-job-controller.name" . }}
{{ include "batch-job-controller.helm-labels" . | indent 4 }}
  name: {{ template "batch-job-controller.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: public
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: internal
      port: 8090
      protocol: TCP
      targetPort: 8090
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    name: {{ template "batch-job-controller.name" . }}
  sessionAffinity: None
  type: ClusterIP