name: e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    name: Run end-2-end Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🖼 Build image
        run: docker build -f Dockerfile --build-arg VERSION=e2e-tests -t batch-job-controller:e2e .

      - name: 🤖 Install kind with registry
        uses: bakito/kind-with-registry-action@b13dc5fd599a5c774e7ca721d6e7a34f7269d2d8 # v1.0.1
        with:
          docker_image_name: batch-job-controller:e2e

      - name: 🚀 Install helm chart
        run: ./testdata/e2e/installChart.sh
      - name: ⏳ Wait for a job pod to be executed
        run: ./testdata/e2e/findExecutedJobPod.sh
      - name: 🧾 Print and check controller logs/events
        run: ./testdata/e2e/checkAndPrintControllerLogsAndEvents.sh


