name: e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    name: Run end-2-end Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v6

      - name: 🖼 Build image
        run: docker build -f Dockerfile --build-arg VERSION=e2e-tests -t batch-job-controller:e2e .

      - name: 🤖 Install kind with registry
        uses: bakito/kind-with-registry-action@main
        with:
          docker_image_name: batch-job-controller:e2e

      - name: 🚀 Install helm chart
        run: ./testdata/e2e/installChart.sh
      - name: ⏳ Wait for a job pod to be executed
        run: ./testdata/e2e/findExecutedJobPod.sh
      - name: 🧾 Print controller logs
        run: ./testdata/e2e/printControllerLogs.sh


