name: Build images

on:
  push:
    branches: main
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push ${{github.event.release.tag_name }}
        id: docker_build_release
        uses: docker/build-push-action@v5
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: true
          tags: ghcr.io/bakito/batch-job-controller:latest,ghcr.io/bakito/batch-job-controller:${{ github.event.release.tag_name }},quay.io/bakito/batch-job-controller:latest,quay.io/bakito/batch-job-controller:${{ github.event.release.tag_name }}
          platforms: linux/amd64
          provenance: false
          build-args: VERSION=${{ github.event.release.tag_name }}

      - name: Build and push main
        id: docker_build_main
        uses: docker/build-push-action@v5
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: true
          tags: ghcr.io/bakito/batch-job-controller:main,quay.io/bakito/batch-job-controller:main
          platforms: linux/amd64
          provenance: false
          build-args: VERSION=main
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
